# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import UrlRn_pb2 as UrlRn__pb2


class UrlRnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createUrl = channel.unary_unary(
                '/urlshortener.UrlRn/createUrl',
                request_serializer=UrlRn__pb2.CreateUrlRequest.SerializeToString,
                response_deserializer=UrlRn__pb2.UrlResponse.FromString,
                )
        self.listUserUrls = channel.unary_unary(
                '/urlshortener.UrlRn/listUserUrls',
                request_serializer=UrlRn__pb2.UserUrlsRequest.SerializeToString,
                response_deserializer=UrlRn__pb2.UrlListResponse.FromString,
                )


class UrlRnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listUserUrls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrlRnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.createUrl,
                    request_deserializer=UrlRn__pb2.CreateUrlRequest.FromString,
                    response_serializer=UrlRn__pb2.UrlResponse.SerializeToString,
            ),
            'listUserUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.listUserUrls,
                    request_deserializer=UrlRn__pb2.UserUrlsRequest.FromString,
                    response_serializer=UrlRn__pb2.UrlListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'urlshortener.UrlRn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UrlRn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/urlshortener.UrlRn/createUrl',
            UrlRn__pb2.CreateUrlRequest.SerializeToString,
            UrlRn__pb2.UrlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listUserUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/urlshortener.UrlRn/listUserUrls',
            UrlRn__pb2.UserUrlsRequest.SerializeToString,
            UrlRn__pb2.UrlListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
