# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UrlRn.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bUrlRn.proto\x12\x0curlshortener\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\" \n\x0cUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\"=\n\x10UserListResponse\x12)\n\x05users\x18\x01 \x03(\x0b\x32\x1a.urlshortener.UserResponse\"#\n\x0fUserUrlsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"e\n\x10\x43reateUrlRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\x12*\n\tstatistic\x18\x03 \x01(\x0b\x32\x17.urlshortener.Statistic\"3\n\nUrlRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\".\n\x04UrlR\x12&\n\x03url\x18\x01 \x01(\x0b\x32\x19.urlshortener.UrlResponse\"m\n\x0bUrlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12.\n\tstatistic\x18\x04 \x01(\x0b\x32\x1b.urlshortener.StatisticList\":\n\x0fUrlListResponse\x12\'\n\x04urls\x18\x01 \x03(\x0b\x32\x19.urlshortener.UrlResponse\"J\n\tStatistic\x12\x0f\n\x07\x62rowser\x18\x01 \x01(\t\x12\x17\n\x0foperatingSystem\x18\x02 \x01(\t\x12\x13\n\x0bipDirection\x18\x03 \x01(\t\";\n\rStatisticList\x12*\n\tstatistic\x18\x01 \x03(\x0b\x32\x17.urlshortener.Statistic2\x9d\x01\n\x05UrlRn\x12\x46\n\tcreateUrl\x12\x1e.urlshortener.CreateUrlRequest\x1a\x19.urlshortener.UrlResponse\x12L\n\x0clistUserUrls\x12\x1d.urlshortener.UserUrlsRequest\x1a\x1d.urlshortener.UrlListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UrlRn_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=91
  _globals['_USERREQUEST']._serialized_end=122
  _globals['_USERRESPONSE']._serialized_start=124
  _globals['_USERRESPONSE']._serialized_end=156
  _globals['_USERLISTRESPONSE']._serialized_start=158
  _globals['_USERLISTRESPONSE']._serialized_end=219
  _globals['_USERURLSREQUEST']._serialized_start=221
  _globals['_USERURLSREQUEST']._serialized_end=256
  _globals['_CREATEURLREQUEST']._serialized_start=258
  _globals['_CREATEURLREQUEST']._serialized_end=359
  _globals['_URLREQUEST']._serialized_start=361
  _globals['_URLREQUEST']._serialized_end=412
  _globals['_URLR']._serialized_start=414
  _globals['_URLR']._serialized_end=460
  _globals['_URLRESPONSE']._serialized_start=462
  _globals['_URLRESPONSE']._serialized_end=571
  _globals['_URLLISTRESPONSE']._serialized_start=573
  _globals['_URLLISTRESPONSE']._serialized_end=631
  _globals['_STATISTIC']._serialized_start=633
  _globals['_STATISTIC']._serialized_end=707
  _globals['_STATISTICLIST']._serialized_start=709
  _globals['_STATISTICLIST']._serialized_end=768
  _globals['_URLRN']._serialized_start=771
  _globals['_URLRN']._serialized_end=928
# @@protoc_insertion_point(module_scope)
